# Generated by Django 5.1 on 2024-09-02 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note_taking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notetype",
            name="created",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="notetype",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notetype",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
    ]
